#!/bin/bash
rm /tmp/dump
xcrun -sdk iphoneos gcc -arch armv7 -mthumb -mcpu=cortex-a8 -std=gnu99 -D__IOS__ -miphoneos-version-min=$1 -fmessage-length=0  -Wreturn-type -Wunused-variable -pipe -Wno-trigraphs -fpascal-strings --sysroot=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS$1.sdk ./tool/dump.c -isysroot /Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS$1.sdk -o /tmp/dump
otool -tv /tmp/dump
